# Generated by Django 3.1.5 on 2021-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='widget_name',
            field=models.CharField(default='kitchen', max_length=20),
        ),
    ]
